import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navBar'

export default function Home() {
  const [receiptId, setReceiptId] = useState('')

  function scanQR(evt) {
    evt.preventDefault()
    setReceiptId('urllr')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>

      <main className={styles.main}>
        <header className={styles.header}>
        <div className={`${styles.hero_bg}`}>
          <div className={`${styles.title_container} container`}>
            <h1 className={styles.title}>easy laundry</h1>
            <p className={styles.slogan}>easy laundry easy life</p>
            <form action={`/laundry/${receiptId}`} method='get' className={`input-group ${styles.track_input_group}`}>
              <input type="text" className="form-control" placeholder="Receipt ID" aria-label="Recipient's username with two button addons" aria-describedby="button-addon4" value={receiptId} onChange={(evt)=>setReceiptId(evt.target.value)}></input>
              <div className="input-group-append" id="button-addon4">
                <button className="btn btn-light" type="submit">Track</button>
                <button className="btn btn-dark" type="button" onClick={scanQR}>Scan QR</button>
              </div>
            </form>
          </div>
        </div>
        </header>
        <section className='section container mb-5'>
          <div className='d-flex justify-content-center'>
            <h2>Services</h2>
          </div>
          <div className='d-flex justify-content-between flex-wrap flex-sm-nowrap'>
            <div className='card w-100 flex-grow-1 m-1'>
              <div className='card-body'>
                <div className='d-flex justify-content-center m-5'>
                  <Image src='/image/delivery.png' width='100px' height='100px' alt='24/7 icon'></Image>
                </div>
                <h5 className=''>24/7 service</h5>
                <p className='text-black-50'>We are always available at your service. Come by and leave your clothes to us any time of the day.</p>
              </div>
            </div >
            <div className='card w-100 flex-grow-1 m-1'>
              <div className="card-body">
                <div className='d-flex justify-content-center m-5'>
                  <Image src='/image/value.png' width='100px' height='100px' alt='24/7 icon'></Image>
                </div>
                <h5>Handle with care</h5>
                <p className='text-black-50'>No one wants to ruin their favorite shirt or pant. We treasure your clothes as they are ours.</p>
              </div>
            </div>
            <div className='card w-100 flex-grow-1 m-1'>
              <div className="card-body">
                <div className='d-flex justify-content-center m-5'>
                  <Image src='/image/timer.png' width='100px' height='100px' alt='24/7 icon'></Image>
                </div>
                <h5>Ultra fast</h5>
                <p className='text-black-50'>Your time is valuable. Knowing that we always strive to get your order done as soon as possible. Your clothes will be ready as fast as a few hours.</p>
              </div>
            </div>
          </div>            
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
